import Head from 'next/head'
import Header from "@/components/Header/Header";
import Main from "@/components/Main/Main";
import {GetStaticProps, InferGetStaticPropsType} from "next";

type product = {
    id: number
    title: string
    price: number
}

type Shop = {
    carts: product[]
}
export const getStaticProps: GetStaticProps<{
    repo: Shop
}> = async () => {
    const res = await fetch('https://dummyjson.com/carts')
    const repo = await res.json()
    return { props: { repo } }
}
export default function Home({repo,
                             }: InferGetStaticPropsType<typeof getStaticProps>) {
    console.log(repo.carts[0].id)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>{repo.carts.map(el => el.id)}</div>
      <Header/>
      <Main/>
    </>
  )
}
